# https://github.com/robvanderleek/create-issue-branch#option-2-configure-github-action

# ex: i4-lower_camel_upper
branchName: 'is${issue.number}-${issue.title[0,32]}'
branches:
  - label: epic
    skip: true
  - label: debt
    skip: true
